FROM python:latest
#Labels as key value pair
LABEL Maintainer="cosmin"
WORKDIR /usr/app/src
RUN pip install paho-mqtt
RUN pip install Flask
COPY mainAPI.py ./
COPY broker_publish.py ./
COPY broker_subscribe.py ./
CMD [ "python", "./mainAPI.py"]